name: build

on:
  push:
    paths:
      - '**.js'

jobs:
  build:

    name: my job
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [10, 12, 14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        exclude:
          - os: windows-latest
            node-version: 14

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present